stages:
  - sync_to_github

# Sync from GitLab `main` to GitHub (Keeps GitHub Updated)
sync_to_github:
  stage: sync_to_github
  only:
    - main
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "abenavid@redhat.com"
    - git config --global user.name "Alex Benavides"
    - rm -rf tmp_repo
    - git clone https://$GITHUB_PAT@github.com/redhat-cop/ansible-library.git tmp_repo
    - cd tmp_repo
    - git remote add gitlab https://abenavid:$GITLAB_PAT@gitlab.consulting.redhat.com/internal-ansible-library/ansible-library.git
    - git fetch --all
    - git remote -v
    - git checkout main || git checkout -B main origin/main
    - git fetch gitlab main || echo "GitLab main branch not found."

    # Resolve merge conflicts by favoring GitLab changes
    - git merge -X theirs gitlab/main || echo "No changes to merge from GitLab."
    
    - git commit -m "Sync with GitLab main" || echo "No changes to commit."
    - git push --force origin main
  tags:
    - internal
    - pah
